src/routes/companies.py
import logging

from flask import Blueprint, render_template, request, url_for, redirect, flash, send_file
from pydantic import ValidationError

from src.authentication import login_required

from src.database.models.bank_accounts import BusinessBankAccount
from src.database.models.companies import Company, UpdateCompany, CreateCompany, CreateTenantRelationCompany, \
    TenantRelationCompany, CreateTenantCompany, UpdateTenantCompany
from src.database.models.notifications import NotificationsModel
from src.database.models.properties import Property
from src.database.models.users import User
from src.logger import init_logger
from src.main import notifications_controller, company_controller, tenant_controller
from src.reports import create_report
from src.reports.bank_account_report import BankAccountPrintParser
from src.reports.company_report import map_company_to_parser, CompanyPrintParser

companies_route = Blueprint('companies', __name__)
companies_logger = init_logger('companies_logger')
companies_logger.setLevel(logging.INFO)


@companies_route.get('/admin/companies')
@login_required
async def get_companies(user: User):
    context: dict[str, str | list[dict[str, str]]] = user.dict() if user else {}

    companies: list[Company] = await company_controller.get_user_companies(user_id=user.user_id)
    companies_dict = [company.dict() for company in companies if company] if isinstance(companies, list) else []

    notifications: NotificationsModel = await notifications_controller.get_user_notifications(user_id=user.user_id)
    notifications_dicts = [notice.dict() for notice in notifications.unread_notification] if notifications else []

    context |= {
        'companies': companies_dict,
        'notifications_list': notifications_dicts,
    }

    return render_template('companies/companies.html', **context)


@companies_route.get('/admin/company/<string:company_id>')
@login_required
async def get_company(user: User, company_id: str):
    user_data = user.dict()

    company: Company = await company_controller.get_company(company_id=company_id, user_id=user.user_id)
    properties: list[Property] = await company_controller.get_properties(user=user, company_id=company_id)

    bank_accounts: BusinessBankAccount = await company_controller.get_bank_accounts(user=user, company_id=company_id)

    properties_dict = [prop.dict() for prop in properties if prop] if isinstance(properties, list) else []

    bank_accounts_dicts = bank_accounts.dict() if bank_accounts else {}

    notifications: NotificationsModel = await notifications_controller.get_user_notifications(user_id=user.user_id)
    notifications_dicts = [notice.dict() for notice in notifications.unread_notification] if notifications else []

    context = dict(user=user_data,
                   company=company.dict() if isinstance(company, Company) else {},
                   properties=properties_dict,
                   bank_account=bank_accounts_dicts,
                   notifications_list=notifications_dicts)

    return render_template('companies/company.html', **context)


@companies_route.get('/admin/create-company')
@login_required
async def get_create_company(user: User):
    user_data = user.dict()
    notifications: NotificationsModel = await notifications_controller.get_user_notifications(user_id=user.user_id)

    notifications_dicts = [notice.dict() for notice in notifications.unread_notification] if notifications else []

    context = dict(user=user_data, notifications_list=notifications_dicts)

    return render_template('companies/create_company.html', **context)


@companies_route.post('/admin/create-company')
@login_required
async def do_create_company(user: User):
    form_data = request.form
    try:
        company_data = Company(**form_data)

        _company_data = await company_controller.create_company(company=company_data, user=user)

        _message = f"Company {_company_data.company_name} Added Successfully"
        flash(message=_message, category="success")
    except ValidationError as e:
        companies_logger.error(str(e))
        flash(message="Error creating Company please fill in all required fields", category='danger')

    return redirect(url_for('companies.get_companies'), code=302)


@companies_route.post('/admin/edit-company/<string:company_id>')
@login_required
async def do_edit_company(user: User, company_id: str):
    """

    :param user:
    :param company_id:
    :return:
    """
    try:
        company_data: UpdateCompany = UpdateCompany(**request.form)
    except ValidationError:
        message: str = "Error cannot update Company Data, Invalid Fields"
        flash(message=message, category="danger")
        return redirect(url_for('companies.get_company', company_id=company_id))

    _ = await company_controller.update_company(user=user, company_data=company_data)
    flash(message="Successfully Updated Company Data", category="success")
    return redirect(url_for('companies.get_company', company_id=company_id), code=302)


@companies_route.post('/admin/company/add-bank-account/<string:company_id>')
@login_required
async def do_add_bank_account(user: User, company_id: str):
    try:
        bank_account_details: BusinessBankAccount = BusinessBankAccount(**request.form)
        if company_id != bank_account_details.company_id:
            flash(message='Ouch That one hurt ', category="danger")
            return redirect(url_for('home.get_home'))

        account_details = await company_controller.update_bank_account(user=user,
                                                                       account_details=bank_account_details)
        companies_logger.info(account_details)

        flash(message="successfully updated company_id bank account details", category="success")

    except ValidationError as e:
        companies_logger.error(str(e))
        flash(message="Error creating Bank Account please fill in all the details", category="danger")

    return redirect(url_for('companies.get_company', company_id=company_id), code=302)


@companies_route.get('/admin/company/print/<string:company_id>')
@login_required
async def print_company(user: User, company_id: str):
    """

    :param user:
    :param company_id:
    :return:
    """
    user_id = user.user_id

    company_data: Company = await company_controller.get_company(company_id=company_id,
                                                                 user_id=user_id)
    company_bank_account: BusinessBankAccount = await company_controller.get_bank_accounts(user=user,
                                                                                           company_id=company_id)
    properties_list: list[Property] = await company_controller.get_properties(user=user,
                                                                              company_id=company_id)

    _title = f"{company_data.company_name.upper()} Report"
    # TODO - add more data points to print
    company_data: CompanyPrintParser = map_company_to_parser(company=company_data)
    company_data_dict = {}
    if company_bank_account:
        bank_account_data: BankAccountPrintParser = BankAccountPrintParser(**company_bank_account.dict())
        company_data_dict["Bank Account"] = bank_account_data.to_dict()

    company_data_dict |= company_data.to_dict()
    properties_dict = [building.dict() for building
                       in properties_list if building] if isinstance(properties_list, list) else []
    company_data_dict["Properties"] = properties_dict

    document_buffer = create_report(title=_title, data=company_data_dict)

    return send_file(
        path_or_file=document_buffer,
        mimetype='application/pdf',
        as_attachment=True,
        download_name=f"{_title}.pdf")


@companies_route.post('/admin/add-tenants-company')
@login_required
async def add_tenants_company(user: User):
    """
    **add_tenants_company**


    :param user:
    :return:
    """
    tenant_company: CreateTenantCompany = CreateTenantCompany(**request.form)
    tenant_company_relation: CreateTenantRelationCompany = CreateTenantRelationCompany(**tenant_company.dict())
    new_company_data = await company_controller.create_company_internal(company=tenant_company)
    new_company_relation: TenantRelationCompany = await company_controller.create_company_tenant_relation_internal(
        company_relation=tenant_company_relation)

    tenant_data = await tenant_controller.get_tenant_by_id(tenant_id=tenant_company.tenant_id)
    tenant_data.company_id = tenant_company.company_id
    updated_tenant = await tenant_controller.update_tenant(tenant=tenant_data)

    return redirect(url_for('buildings.get_unit', building_id=tenant_company.building_id,
                            unit_id=tenant_company.unit_id), code=302)


@companies_route.post('/admin/update-tenant-company/<string:company_id>')
@login_required
async def update_tenant_company(user: User, company_id: str):
    """

    :param user:
    :param company_id:
    :return:
    """
    tenant_company_data = UpdateTenantCompany(**request.form)
    if company_id == tenant_company_data.company_id:
        updated_company: UpdateTenantCompany | None = await company_controller.update_tenant_company(
            company_data=tenant_company_data)
    else:
        updated_company = None

    if updated_company:
        flash(message=f"updated Tenant Company data : {updated_company.company_name}", category="success")
    else:
        flash(message=f"Unable to Update Company Data : {updated_company.company_name}", category="danger")

    _company_id = tenant_company_data.company_id or company_id
    unit_id = tenant_company_data.unit_id

    return redirect(url_for('buildings.get_unit', building_id=tenant_company_data.building_id, unit_id=unit_id), code=302)

templates/building/units/modals/add_bill_modal.html
<!-- Modal -->
<div class="modal fade" id="addBillModal" tabindex="-1" role="dialog" aria-labelledby="addBillModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addBillModalLabel">Add Bill to Unit</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <span class="font-weight-bold text-black">Used to create Bills for Property Units - This allows for variable billing for items such as Electricity
      and Water
      </span>
        <form action="{{ url_for('buildings.create_billing_charge') }}" method="POST">
            <input type="hidden" class="form-control" id="property_id" name="property_id" value="{{ unit.property_id }}">
            <input type="hidden" class="form-control" id="tenant_id" name="tenant_id" value="{{ unit.tenant_id }}">
            <input type="hidden" class="form-control" id="unit_id" name="unit_id" value="{{ unit.unit_id }}">
          <div class="form-group">
              <select class="form-control" id="item_number" name="item_number">
                  <option value="">Select Billable Item</option>
                  {% for item in billable_items %}
                    <option value="{{ item.item_number }}">
                        {{ item.description }}, <span class="font-weight-bold font-italic text-info">Charge Per Unit = {{ item.multiplier }}</span>
                    </option>
                  {% endfor %}
              </select>
          </div>
          <div class="form-group">
            <label for="amountEntry" class="label font-weight-bold">Amount / Units / Meter Readings Used</label>
            <input type="number" class="form-control" id="amount" name="amount" required>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>

templates/building/units/modals/add_company.html
<!-- Modal dialog -->
<div class="modal fade" id="companyModal" tabindex="-1" role="dialog" aria-labelledby="companyModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="companyModalLabel">Enter Tenant Company Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <span class="card-content font-weight-bold font-italic text-info"> Use this form to enter company details associated with the Tenant
                    or the company who will be making use of the Unit and therefore also responsible for
                    lease agreements &amp; payments
                </span>
                <div class="card-footer">
                    <form id="TenantCompanyForm"
                          class="form-horizontal"
                          action="{{ url_for('companies.add_tenants_company') }}"
                          enctype="application/x-www-form-urlencoded"
                          method="POST"
                    >

                        <input type="hidden" value="{{ unit.tenant_id }}" name="tenant_id"/>
                        <input type="hidden" value="{{ unit.property_id }}" name="building_id" />
                        <input type="hidden" value="{{ unit.unit_id }}" name="unit_id" />

                        <div class="form-group">
                            <label for="companyName">Company Name</label>
                            <input type="text" class="form-control" id="companyName" name="company_name" required>
                        </div>
                        <div class="form-group">
                            <label for="address">Address</label>
                            <input type="text" class="form-control" id="address" name="address_line_1" required>
                        </div>
                        <div class="form-group">
                            <label for="city">City</label>
                            <input type="text" class="form-control" id="city" name="city" required>
                        </div>
                        <div class="form-group">
                            <label for="state">Province</label>
                            <input type="text" class="form-control" id="province" name="province" required>
                        </div>
                        <div class="form-group">
                            <label for="country">Country</label>
                            <input type="text" class="form-control" id="country" name="country" required>
                        </div>
                        <div class="form-group">
                            <label for="postalCode">Postal Code</label>
                            <input type="text" class="form-control" id="postalCode" name="postal_code" required>
                        </div>
                        <div class="form-group">
                            <label for="contactNumber">Contact Number</label>
                            <input type="text" class="form-control" id="contactNumber" name="contact_number" required>
                        </div>
                        <div class="form-group">
                            <label for="website">Website</label>
                            <input type="text" class="form-control" id="website" name="website" required>
                        </div>
                        <button type="submit" class="btn btn-sm btn-primary">
                            <i class="ti-save"> </i>
                            Save
                        </button>
                        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal" aria-label="Close">
                            <i class="ti-close"> </i>
                            Close
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

templates/building/units/modals/edit_company.html
<!-- Modal dialog -->
<div class="modal fade" id="editcompanyModal" tabindex="-1" role="dialog" aria-labelledby="editcompanyModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editcompanyModalLabel">Edit Tenant Company Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <span class="card-content font-weight-bold font-italic text-info"> Use this form to enter company details associated with the Tenant
                    or the company who will be making use of the Unit and therefore also responsible for
                    lease agreements &amp; payments
                </span>
                <div class="card-footer">
                    <form id="TenantCompanyForm"
                          class="form-horizontal"
                          {% if company %}
                            action="{{ url_for('companies.update_tenant_company', company_id=company.company_id) }}"
                          {% else %}
                            action="#"
                          {% endif %}
                          enctype="application/x-www-form-urlencoded"
                          method="POST"
                    >

                        <input type="hidden" value="{{ unit.tenant_id }}" name="tenant_id"/>
                        <input type="hidden" value="{{ unit.property_id }}" name="building_id" />
                        <input type="hidden" value="{{ unit.unit_id }}" name="unit_id" />
                        <input type="hidden" value="{{ company.company_id }}" name="company_id"/>

                    <div class="form-group">
                        <label for="companyName">Company Name</label>
                        <input type="text" class="form-control" id="companyName" name="company_name"
                               value="{{ company.company_name }}"
                               required>
                    </div>
                    <div class="form-group">
                        <label for="address">Address</label>
                        <input type="text" class="form-control" id="address" name="address_line_1"
                               value="{{ company.address_line_1 }}"
                               required>
                    </div>

                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="form-group">
                                <label for="city">City</label>
                                <input type="text" class="form-control" id="city" name="city"
                                       value="{{ company.city }}"
                                       required>
                            </div>
                            <div class="form-group">
                                <label for="state">Province</label>
                                <input type="text" class="form-control" id="province" name="province"
                                       value="{{ company.province }}"
                                       required>
                            </div>
                            <div class="form-group">
                                <label for="country">Country</label>
                                <input type="text" class="form-control" id="country" name="country"
                                       value="{{ company.country }}"
                                       required>
                            </div>

                        </div>

                        <div class="col-lg-6 col-md-6 col-sm-6">

                        <div class="form-group">
                            <label for="postalCode">Postal Code</label>
                            <input type="text" class="form-control" id="postalCode" name="postal_code"
                                   value="{{ company.postal_code }}"
                                   required>
                        </div>
                        <div class="form-group">
                            <label for="contactNumber">Contact Number</label>
                            <input type="text" class="form-control" id="contactNumber" name="contact_number"
                                   value="{{ company.contact_number }}"
                                   required>
                        </div>
                        <div class="form-group">
                            <label for="website">Website</label>
                            <input type="text" class="form-control" id="website" name="website"
                                   value="{{ company.website }}"
                                   required>
                        </div>
                        </div>
                    </div>
                        <button type="submit" class="btn btn-sm btn-primary">
                            <i class="ti-save"> </i>
                            Save
                        </button>
                        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal" aria-label="Close">
                            <i class="ti-close"> </i>
                            Close
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

templates/building/units/modals/edit_tenant.html
<!-- Edit Tenant Modal -->
<div class="modal fade" id="editTenantModal" tabindex="-1" role="dialog" aria-labelledby="editTenantModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editTenantModalLabel">Edit Tenant</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('buildings.update_tenant_to_building_unit', building_id=unit.property_id, unit_id=unit.unit_id) }}" method="post">
          <!-- including Unit Data on Form -->
          <input type="hidden" name="property_id" value="{{ unit.property_id }}" />
          <input type="hidden" name="unit_id" value="{{ unit.unit_id }}" />
          <input type="hidden" name="unit_number" value="{{ unit.unit_number }}" />
          <input type="hidden" name="rental_amount" value="{{ unit.rental_amount }}" />
          <input type="hidden" name="unit_area" value="{{ unit.unit_area }}" />
          <input type="hidden" name="has_reception" value="{{ unit.has_reception }}" />
          <!--- Done --->

          <!-- tenant data -->
          <input type="hidden" name="tenant_id" value="{{ unit.tenant_id }}" />

          <div class="mb-3">
            <label for="name" class="form-label">Name:</label>
            <input type="text" class="form-control" id="name" name="name"
                   value="{{ tenant.name }}"
                   required>
          </div>

          <div class="mb-3">
            <label for="id_number" class="form-label">ID Number:</label>
            <input type="text" class="form-control" id="id_number" name="id_number"
                   value="{{ tenant.id_number }}"
                   required>
          </div>

          <div class="mb-3">
            <label for="email" class="form-label">Email:</label>
            <input type="email" class="form-control" id="email" name="email"
                   value="{{ tenant.email }}"
                   required>
          </div>

          <div class="mb-3">
            <label for="cell" class="form-label">Phone Number:</label>
            <input type="text" class="form-control" id="cell" name="cell"
                   value="{{ tenant.cell }}"
                   required>
          </div>

          <div class="mb-3">
            <label for="is_renting" class="form-label">Is Renting:</label>
            <select class="form-control" id="is_renting" name="is_renting" required>
              <option value="true">True</option>
              <option value="false">False</option>
            </select>
          </div>

          <div class="mb-3">
            <label for="lease-start-date" class="form-label">Lease Start Date:</label>
            <input type="date" class="form-control" id="lease_start_date"
                   value="{{ tenant.lease_start_date }}"
                   name="lease_start_date">
          </div>

          <div class="mb-3">
            <label for="lease-end-date" class="form-label">Lease End Date:</label>
            <input type="date" class="form-control" id="lease_end_date"
                   value="{{ tenant.lease_end_date }}"
                   name="lease_end_date">
          </div>

          <button type="submit" class="btn btn-primary">
            <span class="font-weight-bold">
              <i class="ti-save"></i>
              Update
            </span>
          </button>
          <button type="reset" class="btn btn-danger">
            <span class="font-weight-bold">
              <i class="ti-close"></i>
              Cancel
            </span>
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

templates/building/units/modals/edit_unit.html
<div class="modal fade" id="editUnitModal" tabindex="-1" role="dialog" aria-labelledby="editUnitModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editUnitModalLabel">Unit Editor</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <span class="font-weight-bold text-black">Used to update Unit Details</span>
        <form action="{{ url_for('buildings.updated_unit', unit_id=unit.unit_id) }}"
              method="POST" enctype="application/x-www-form-urlencoded">

            <input type="hidden" name="property_id" value="{{ unit.property_id }}" readonly>
            <input type="hidden" name="unit_id" value="{{ unit.unit_id }}" readonly>
            <input type="hidden" name="tenant_id" value="{{ unit.tenant_id }}" readonly>


          <div class="form-group">
            <label for="unit_number">Unit Number</label>
            <input type="text" class="form-control" id="unit_number"
                   name="unit_number" value="{{ unit.unit_number }}" required>
          </div>

          <div class="form-group">
            <label for="rental_amount">Rental Amount</label>
            <input type="number" class="form-control" id="rental_amount"
                   name="rental_amount" value="{{ unit.rental_amount }}" required>
          </div>

          <div class="form-group">
            <label for="lease_start_date">Lease Start Date</label>
            <input type="date" class="form-control" id="lease_start_date"
                   name="lease_start_date" value="{{ unit.lease_start_date }}" required>
          </div>

          <div class="form-group">
            <label for="lease_end_date">Lease End Date</label>
            <input type="date" class="form-control" id="lease_end_date"
                   name="lease_end_date" value="{{ unit.lease_end_date }}" required>
          </div>

          <div class="form-group">
            <label for="unit_area">Unit Area (sqm)</label>
            <input type="number" class="form-control" id="unit_area"
                   name="unit_area" value="{{ unit.unit_area }}" required>
          </div>

          <div class="form-group">
            <label for="has_reception">Has Reception</label>
            <select class="form-control" id="has_reception" name="has_reception">
              <option value="true" {% if unit.has_reception %}selected{% endif %}>True</option>
              <option value="false" {% if not unit.has_reception %}selected{% endif %}>False</option>
            </select>
          </div>

            <button type="submit" class="btn btn-sm btn-primary">
                <i class="ti-save"> </i>
                Save
            </button>

            <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal" aria-label="Close">
                <i class="ti-close"> </i>
              close
            </button>

        </form>
      </div>
    </div>
  </div>
</div>