src/database/models/companies.py
import uuid

from pydantic import BaseModel, Field, Extra


class Company(BaseModel):
    """
    Represents the details of a company_id.

    Attributes:
    - company_name (str): The name of the company_id.
    - address (str): The address of the company_id.
    - city (str): The city where the company_id is located.
    - state (str): The state where the company_id is located.
    - country (str): The country where the company_id is located.
    - postal_code (str): The postal code of the company_id's address.
    - contact_number (str): The contact number of the company_id.
    - website (str): The website URL of the company_id.
    """

    company_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    company_name: str | None
    description: str | None

    address_line_1: str | None
    address_line_2: str | None
    city: str | None
    postal_code: str | None
    province: str | None
    country: str | None
    contact_number: str | None
    website: str | None

    class Config:
        from_orm = True
        extra = Extra.ignore


class UpdateCompany(BaseModel):
    company_id: str
    company_name: str
    description: str

    address_line_1: str | None
    address_line_2: str | None
    city: str
    postal_code: str
    province: str
    country: str
    contact_number: str
    website: str


class CreateCompany(BaseModel):
    """
    Represents the details of a company_id.

    Attributes:
    - company_name (str): The name of the company_id.
    - address (str): The address of the company_id.
    - city (str): The city where the company_id is located.
    - state (str): The state where the company_id is located.
    - country (str): The country where the company_id is located.
    - postal_code (str): The postal code of the company_id's address.
    - contact_number (str): The contact number of the company_id.
    - website (str): The website URL of the company_id.
    """

    company_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    company_name: str | None
    description: str | None

    address_line_1: str | None
    address_line_2: str | None
    city: str | None
    postal_code: str | None
    province: str | None
    country: str | None
    contact_number: str | None
    website: str | None


class CreateTenantCompany(BaseModel):
    """
    Represents the details of a company_id.

    Attributes:
    - company_name (str): The name of the company_id.
    - address (str): The address of the company_id.
    - city (str): The city where the company_id is located.
    - state (str): The state where the company_id is located.
    - country (str): The country where the company_id is located.
    - postal_code (str): The postal code of the company_id's address.
    - contact_number (str): The contact number of the company_id.
    - website (str): The website URL of the company_id.
    """

    company_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    tenant_id: str
    building_id: str
    unit_id: str
    company_name: str | None
    description: str | None

    address_line_1: str | None
    address_line_2: str | None
    city: str | None
    postal_code: str | None
    province: str | None
    country: str | None
    contact_number: str | None
    website: str | None


class UpdateTenantCompany(BaseModel):
    """

    """
    company_id: str
    tenant_id: str
    building_id: str
    unit_id: str
    company_name: str | None
    description: str | None

    address_line_1: str | None
    address_line_2: str | None
    city: str | None
    postal_code: str | None
    province: str | None
    country: str | None
    contact_number: str | None
    website: str | None


class CreateTenantRelationCompany(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    company_id: str
    tenant_id: str

    class Config:
        extra = Extra.ignore


class TenantRelationCompany(BaseModel):
    id: str
    company_id: str
    tenant_id: str

src/routes/companies.py
import logging

from flask import Blueprint, render_template, request, url_for, redirect, flash, send_file
from pydantic import ValidationError

from src.authentication import login_required

from src.database.models.bank_accounts import BusinessBankAccount
from src.database.models.companies import Company, UpdateCompany, CreateCompany, CreateTenantRelationCompany, \
    TenantRelationCompany, CreateTenantCompany, UpdateTenantCompany
from src.database.models.notifications import NotificationsModel
from src.database.models.properties import Property
from src.database.models.users import User
from src.logger import init_logger
from src.main import notifications_controller, company_controller, tenant_controller
from src.reports import create_report
from src.reports.bank_account_report import BankAccountPrintParser
from src.reports.company_report import map_company_to_parser, CompanyPrintParser

companies_route = Blueprint('companies', __name__)
companies_logger = init_logger('companies_logger')
companies_logger.setLevel(logging.INFO)


@companies_route.get('/admin/companies')
@login_required
async def get_companies(user: User):
    context: dict[str, str | list[dict[str, str]]] = user.dict() if user else {}

    companies: list[Company] = await company_controller.get_user_companies(user_id=user.user_id)
    companies_dict = [company.dict() for company in companies if company] if isinstance(companies, list) else []

    notifications: NotificationsModel = await notifications_controller.get_user_notifications(user_id=user.user_id)
    notifications_dicts = [notice.dict() for notice in notifications.unread_notification] if notifications else []

    context |= {
        'companies': companies_dict,
        'notifications_list': notifications_dicts,
    }

    return render_template('companies/companies.html', **context)


@companies_route.get('/admin/company/<string:company_id>')
@login_required
async def get_company(user: User, company_id: str):
    user_data = user.dict()

    company: Company = await company_controller.get_company(company_id=company_id, user_id=user.user_id)
    properties: list[Property] = await company_controller.get_properties(user=user, company_id=company_id)

    bank_accounts: BusinessBankAccount = await company_controller.get_bank_accounts(user=user, company_id=company_id)

    properties_dict = [prop.dict() for prop in properties if prop] if isinstance(properties, list) else []

    bank_accounts_dicts = bank_accounts.dict() if bank_accounts else {}

    notifications: NotificationsModel = await notifications_controller.get_user_notifications(user_id=user.user_id)
    notifications_dicts = [notice.dict() for notice in notifications.unread_notification] if notifications else []

    context = dict(user=user_data,
                   company=company.dict() if isinstance(company, Company) else {},
                   properties=properties_dict,
                   bank_account=bank_accounts_dicts,
                   notifications_list=notifications_dicts)

    return render_template('companies/company.html', **context)


@companies_route.get('/admin/create-company')
@login_required
async def get_create_company(user: User):
    user_data = user.dict()
    notifications: NotificationsModel = await notifications_controller.get_user_notifications(user_id=user.user_id)

    notifications_dicts = [notice.dict() for notice in notifications.unread_notification] if notifications else []

    context = dict(user=user_data, notifications_list=notifications_dicts)

    return render_template('companies/create_company.html', **context)


@companies_route.post('/admin/create-company')
@login_required
async def do_create_company(user: User):
    form_data = request.form
    try:
        company_data = Company(**form_data)

        _company_data = await company_controller.create_company(company=company_data, user=user)

        _message = f"Company {_company_data.company_name} Added Successfully"
        flash(message=_message, category="success")
    except ValidationError as e:
        companies_logger.error(str(e))
        flash(message="Error creating Company please fill in all required fields", category='danger')

    return redirect(url_for('companies.get_companies'), code=302)


@companies_route.post('/admin/edit-company/<string:company_id>')
@login_required
async def do_edit_company(user: User, company_id: str):
    """

    :param user:
    :param company_id:
    :return:
    """
    try:
        company_data: UpdateCompany = UpdateCompany(**request.form)
    except ValidationError:
        message: str = "Error cannot update Company Data, Invalid Fields"
        flash(message=message, category="danger")
        return redirect(url_for('companies.get_company', company_id=company_id))

    _ = await company_controller.update_company(user=user, company_data=company_data)
    flash(message="Successfully Updated Company Data", category="success")
    return redirect(url_for('companies.get_company', company_id=company_id), code=302)


@companies_route.post('/admin/company/add-bank-account/<string:company_id>')
@login_required
async def do_add_bank_account(user: User, company_id: str):
    try:
        bank_account_details: BusinessBankAccount = BusinessBankAccount(**request.form)
        if company_id != bank_account_details.company_id:
            flash(message='Ouch That one hurt ', category="danger")
            return redirect(url_for('home.get_home'))

        account_details = await company_controller.update_bank_account(user=user,
                                                                       account_details=bank_account_details)
        companies_logger.info(account_details)

        flash(message="successfully updated company_id bank account details", category="success")

    except ValidationError as e:
        companies_logger.error(str(e))
        flash(message="Error creating Bank Account please fill in all the details", category="danger")

    return redirect(url_for('companies.get_company', company_id=company_id), code=302)


@companies_route.get('/admin/company/print/<string:company_id>')
@login_required
async def print_company(user: User, company_id: str):
    """

    :param user:
    :param company_id:
    :return:
    """
    user_id = user.user_id

    company_data: Company = await company_controller.get_company(company_id=company_id,
                                                                 user_id=user_id)
    company_bank_account: BusinessBankAccount = await company_controller.get_bank_accounts(user=user,
                                                                                           company_id=company_id)
    properties_list: list[Property] = await company_controller.get_properties(user=user,
                                                                              company_id=company_id)

    _title = f"{company_data.company_name.upper()} Report"
    # TODO - add more data points to print
    company_data: CompanyPrintParser = map_company_to_parser(company=company_data)
    company_data_dict = {}
    if company_bank_account:
        bank_account_data: BankAccountPrintParser = BankAccountPrintParser(**company_bank_account.dict())
        company_data_dict["Bank Account"] = bank_account_data.to_dict()

    company_data_dict |= company_data.to_dict()
    properties_dict = [building.dict() for building
                       in properties_list if building] if isinstance(properties_list, list) else []
    company_data_dict["Properties"] = properties_dict

    document_buffer = create_report(title=_title, data=company_data_dict)

    return send_file(
        path_or_file=document_buffer,
        mimetype='application/pdf',
        as_attachment=True,
        download_name=f"{_title}.pdf")


@companies_route.post('/admin/add-tenants-company')
@login_required
async def add_tenants_company(user: User):
    """
    **add_tenants_company**


    :param user:
    :return:
    """
    tenant_company: CreateTenantCompany = CreateTenantCompany(**request.form)
    tenant_company_relation: CreateTenantRelationCompany = CreateTenantRelationCompany(**tenant_company.dict())
    new_company_data = await company_controller.create_company_internal(company=tenant_company)
    new_company_relation: TenantRelationCompany = await company_controller.create_company_tenant_relation_internal(
        company_relation=tenant_company_relation)

    tenant_data = await tenant_controller.get_tenant_by_id(tenant_id=tenant_company.tenant_id)
    tenant_data.company_id = tenant_company.company_id
    updated_tenant = await tenant_controller.update_tenant(tenant=tenant_data)

    return redirect(url_for('buildings.get_unit', building_id=tenant_company.building_id,
                            unit_id=tenant_company.unit_id), code=302)


@companies_route.post('/admin/update-tenant-company/<string:company_id>')
@login_required
async def update_tenant_company(user: User, company_id: str):
    """

    :param user:
    :param company_id:
    :return:
    """
    tenant_company_data = UpdateTenantCompany(**request.form)
    if company_id == tenant_company_data.company_id:
        updated_company: UpdateTenantCompany | None = await company_controller.update_tenant_company(
            company_data=tenant_company_data)
    else:
        updated_company = None

    if updated_company:
        flash(message=f"updated Tenant Company data : {updated_company.company_name}", category="success")
    else:
        flash(message=f"Unable to Update Company Data : {updated_company.company_name}", category="danger")

    _company_id = tenant_company_data.company_id or company_id
    unit_id = tenant_company_data.unit_id

    return redirect(url_for('buildings.get_unit', building_id=tenant_company_data.building_id, unit_id=unit_id), code=302)

templates/companies/companies.html
{% extends "layouts/page.html" %}

{% block content %}
                <section id="main-content">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                            <div class="card-header d-flex justify-content-between align-items-center">
                                <h3 class="card-title">Property Development Companies</h3>
                                <div>
                                    <a href="{{ url_for('companies.get_create_company') }}"
                                       class="btn btn-sm btn-info rm-2"><i class="ti-save"> </i> Add Company</a>
                                </div>
                            </div>
                                <div class="bootstrap-data-table-panel">
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <table id="bootstrap-data-table-export" class="table table-responsive-md table-responsive-lg table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>Company Name</th>
                                                    <th>Address</th>
                                                    <th class="d-none d-sm-table-cell">City</th>
                                                    <th class="d-none d-sm-table-cell">Code</th>
                                                    <th class="d-none d-sm-table-cell">Province</th>
                                                    <th class="d-none d-sm-table-cell">Country</th>
                                                    <th class="d-none d-sm-table-cell"><i class="ti-check-box"> </i> </th>
                                                </tr>
                                            </thead>
                                            {% if companies %}
                                            <tbody>

                                                {% for company in companies %}
                                                    <tr>
                                                        <td> <a href="{{ url_for('companies.get_company', company_id=company.company_id)}}" class="text text-info font-weight-bold"> {{ company.company_name or '' }} </a></td>
                                                        <td>{{ company.address_line_1 or '' }}</td>
                                                        <td class="d-none d-sm-table-cell">{{ company.city or '' }}</td>
                                                        <td class="d-none d-sm-table-cell">{{ company.postal_code or '' }}</td>
                                                        <td class="d-none d-sm-table-cell">{{ company.province or '' }}</td>
                                                        <td class="d-none d-sm-table-cell">{{ company.country or '' }}</td>
                                                        <td class="d-none d-sm-table-cell"><a href="{{ url_for('companies.get_company', company_id=company.company_id)}}"> Open</a> </td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>

                                            {% else %}
                                                <span class="font-weight-bold alert">Please Add your Company In order to begin...</span>
                                            {% endif %}
                                        </table>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </section>
{% endblock %}

{% block scripts %}

{% endblock %}

templates/companies/company.html
{% extends "layouts/page.html" %}

{% block content %}
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h3 class="card-title"><i class="ti-briefcase"> </i> Company Details</h3>
            <div>
                <a href="{{ url_for('companies.get_companies') }}" class="btn btn-sm btn-warning mr-2 mr-md-12 mb-2 mb-md-0">
                    <i class="ti-briefcase"></i> Companies
                </a>
                <a href="#" class="btn btn-sm btn-success mr-2 mr-md-12 mb-2 mb-md-0" data-toggle="modal" data-target="#companyDetailModal">
                    <i class="ti-desktop"></i> Edit
                </a>
                <a href="{{ url_for('companies.print_company', company_id=company.company_id) }}" class="btn btn-sm btn-default mr-2 mr-md-12 mb-2 mb-md-0">
                    <i class="ti-printer"></i> Print
                </a>

            </div>
        </div>
        <div class="card-body">
            <h4>{{ company.company_name }}</h4>
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Location:</strong> {{ company.address_line_1 }}</li>
                        <li  class="list-group-item"><strong>City:</strong> {{ company.city }}</li>
                        <li  class="list-group-item"><strong>Postal Code:</strong> {{ company.postal_code }}</li>
                        <li class="list-group-item"><strong>Province:</strong> {{ company.province }}</li>
                        <li class="list-group-item"><strong>Country:</strong> {{ company.country }}</li>
                    </ul>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12">
                        <ul class="list-group">
                            <li class="list-group-item"><strong>Contact Number:</strong> {{ company.contact_number }}</li>
                            <li class="list-group-item"><strong>Website:</strong> <a href="{{ company.website }}" class="alert-link">{{ company.website }}</a></li>

                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                <button class="btn btn-sm btn-primary" data-toggle="modal" data-target="#bankAccountModal">
                                    <span class="ti-wallet"></span> Bank Account
                                </button>
                                <button class="btn btn-sm btn-success ml-auto" data-toggle="modal" data-target="#showAccountModal">
                                    <span class="ti-view-list"></span> Show Bank Account
                                </button>
                            </li>

                            <div class="alert alert-primary alert-dismissible fade show">
                              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                              <strong>Bank Account!</strong> You can add the bank account details for the company by clicking on the "Bank Account" button.
                                This will allow you to enter the necessary information for managing financial transactions.
                            </div>

                        </ul>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <h3 class="card-title"><i class="ti-info"></i> Description</h3>
            <span class="card-text">{{ company.description }}</span>
        </div>
    </div>

{% include "companies/flow/properties.html" %}
<!--- Modals -->
<!-- Bank Account Modal -->
{% include "companies/modals/bank_account.html" %}
{% include "companies/modals/show_bank_account.html" %}
<!-- Company Details Editor -->
{% include "companies/modals/company_editor.html" %}

{% endblock %}

templates/companies/create_company.html
{% extends "layouts/page.html" %}

{% block content %}
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Capture Company Details</h3>
                </div>
                <div class="input-states">
                    <form action="{{ url_for('companies.do_create_company') }}" method="POST" enctype="application/x-www-form-urlencoded" class="form-horizontal">
                        <div class="form-group has-success">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="form-label">
                                        <i class="ti-layout"></i>
                                        Company Name
                                    </label>
                                    <input type="text" class="form-control" name="company_name">
                                </div>
                            </div>
                        </div>
                        <div class="form-group has-success">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="form-label">
                                        <i class="ti-info"></i>
                                        Company Description
                                    </label>
                                    <textarea type="text" class="form-control" name="description"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="form-group has-success">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="form-label">
                                        <i class="ti-location-pin"></i>
                                        Address Line 1
                                    </label>
                                    <input type="text" class="form-control" name="address_line_1">
                                </div>
                            </div>
                        </div>
                        <div class="form-group has-success">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="form-label">
                                        <i class="ti-location-pin"></i>
                                        Address Line 2
                                    </label>
                                    <input type="text" class="form-control" name="address_line_2">
                                </div>
                            </div>
                        </div>
                        <div class="form-group has-success">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="form-label">
                                        <i class="ti-world"></i>
                                        City / Town
                                    </label>
                                    <input type="text" class="form-control" name="city">
                                </div>
                            </div>
                        </div>
                        <div class="form-group has-success">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="form-label">
                                        <i class="ti-location-pin"></i>
                                        Postal Code
                                    </label>
                                    <input type="text" class="form-control" name="postal_code">
                                </div>
                            </div>
                        </div>
                        <div class="form-group has-success">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="form-label">
                                        <i class="ti-flag"></i>
                                        Province
                                    </label>
                                    <input type="text" class="form-control" name="province">
                                </div>
                            </div>
                        </div>
                        <div class="form-group has-success">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="form-label">
                                        <i class="ti-world"></i>
                                        Country
                                    </label>
                                    <input type="text" class="form-control" name="country">
                                </div>
                            </div>
                        </div>
                        <div class="form-group has-success">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="form-label">
                                        <i class="ti-mobile"></i>
                                        Contact Number
                                    </label>
                                    <input type="text" class="form-control" name="contact_number">
                                </div>
                            </div>
                        </div>
                        <div class="form-group has-success">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label class="form-label">
                                        <i class="ti-link"></i>
                                        Website
                                    </label>
                                    <input type="text" class="form-control" name="website">
                                </div>
                            </div>
                        </div>
                        <div class="form-group has-info">
                            <div class="row">
                                <div class="col-sm-offset-3 col-sm-9">
                                    <button class="btn btn-info mg-r-2">
                                        <i class="ti-save"></i>
                                        Save &amp; Proceed
                                    </button>
                                    <a href="{{ url_for('companies.get_companies') }}" class="btn btn-danger">
                                        <i class="ti-close"></i>
                                        Cancel
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Company Details</h3>
                </div>
                <div class="card-body">
                    <span class="card-content">
                        <p class="font-weight-bold">
                            Companies are used to organize Properties. A company represents a distinct entity or organization within your business. It can be a real estate agency, a property management company, or any other type of business entity that owns or manages properties.
                        </p>
                        <p class="font-weight-bold">
                            By creating companies, you can categorize and manage your properties more efficiently. Each property can be associated with a specific company, allowing you to easily track and distinguish properties based on their ownership or management.
                        </p>
                        <p class="font-weight-bold">
                            It is essential to define at least one or more companies under which your properties will be classified. This enables you to organize and streamline your property management processes effectively.
                        </p>
                        <p class="font-weight-bold">
                            To get started, simply fill out the form on the left with the necessary company details, such as the company name, description, address, contact information, and website. Click the "Save &amp; Proceed" button to create the company and proceed to the next steps.
                        </p>
                    </span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}