src/routes/buildings.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from pydantic import ValidationError

from src.database.models.invoices import CreateInvoicedItem, BillableItem, CreateUnitCharge
from src.logger import init_logger
from src.database.models.lease import LeaseAgreement, CreateLeaseAgreement
from src.database.models.tenants import Tenant
from src.database.models.notifications import NotificationsModel
from src.main import company_controller, notifications_controller, tenant_controller, lease_agreement_controller
from src.database.models.properties import Property, Unit, AddUnit, UpdateProperty, CreateProperty, UpdateUnit
from src.database.models.companies import Company
from src.database.models.users import User
from src.authentication import login_required

buildings_route = Blueprint('buildings', __name__)
buildings_logger = init_logger("Buildings-Router")


async def get_common_context(user: User, building_id: str, property_editor: bool = False):
    user_data = user.dict()
    building_property: Property = await company_controller.get_property(user=user, property_id=building_id)
    property_units: list[Unit] = await company_controller.get_property_units(user=user, property_id=building_id)
    notifications: NotificationsModel = await notifications_controller.get_user_notifications(user_id=user.user_id)

    notifications_dicts = [notice.dict() for notice in notifications.unread_notification] if notifications else []
    billable_items_: list[BillableItem] = await company_controller.get_billable_items(building_id=building_id)
    billable_dicts = [bill.dict() for bill in billable_items_ if bill and not bill.deleted] if billable_items_ else []

    return dict(
        user=user_data,
        property=building_property.dict(),
        property_editor=property_editor,
        notifications_list=notifications_dicts,
        units=[unit.dict() for unit in property_units],
        billable_items=billable_dicts,
    )


@buildings_route.get('/admin/buildings')
@login_required
async def get_buildings(user: User):
    user_data = user.dict()
    notifications: NotificationsModel = await notifications_controller.get_user_notifications(user_id=user.user_id)

    notifications_dicts = [notice.dict() for notice in notifications.unread_notification] if notifications else []

    context = dict(user=user_data, notifications_list=notifications_dicts)
    return render_template('building/buildings.html', **context)


@buildings_route.get('/admin/building/<string:building_id>')
@login_required
async def get_building(user: User, building_id: str):
    """
        returns a specific building by building id
    :param user:
    :param building_id:
    :return:
    """
    context = await get_common_context(user=user,
                                       building_id=building_id)

    return render_template('building/building.html', **context)


@buildings_route.get('/admin/add-building/<string:company_id>')
@login_required
async def add_building(user: User, company_id: str):
    user_data = user.dict()

    company: Company = await company_controller.get_company(company_id=company_id, user_id=user.user_id)
    notifications: NotificationsModel = await notifications_controller.get_user_notifications(user_id=user.user_id)

    notifications_dicts = [notice.dict() for notice in notifications.unread_notification] if notifications else []

    context = dict(user=user_data,
                   company=company.dict(), notifications_list=notifications_dicts)

    return render_template('building/add_building.html', **context)


@buildings_route.post('/admin/add-building/<string:company_id>')
@login_required
async def do_add_building(user: User, company_id: str):
    _ = user.dict()

    company: Company = await company_controller.get_company(company_id=company_id, user_id=user.user_id)
    property_data: CreateProperty = CreateProperty(**request.form)
    property_data.company_id = company.company_id
    property_model: Property = await company_controller.add_property(user=user, _property=property_data)

    _message: str = f"Property : {property_model.name.title()} Successfully added to : {company.company_name.title()}"
    flash(message=_message, category="success")
    return redirect(url_for('companies.get_company', company_id=company.company_id), code=302)


@buildings_route.get('/admin/edit-building/<string:building_id>')
@login_required
async def edit_building(user: User, building_id: str):
    context = await get_common_context(user, building_id, property_editor=True)
    return render_template('building/building.html', **context)


@buildings_route.post('/admin/edit-building/<string:building_id>')
@login_required
async def do_edit_building(user: User, building_id: str):
    try:
        updated_building: UpdateProperty = UpdateProperty(**request.form)
        _property = await company_controller.update_property(user=user, property_details=updated_building)
        if _property is not None:
            flash(message="Successfully updated Property/Building", category="success")
    except ValidationError as e:
        print(f"error {str(e)}")
        flash(message="Error updating Property/Building...", category="danger")

    context = await get_common_context(user=user, building_id=building_id)
    return render_template('building/building.html', **context)


@buildings_route.post('/admin/add-unit/<string:building_id>')
@login_required
async def do_add_unit(user: User, building_id: str):
    _ = user.dict()
    try:
        unit_data: AddUnit = AddUnit(**request.form)

        _ = await company_controller.add_unit(user=user, unit_data=unit_data, property_id=building_id)
        flash(message="Unit Added Successfully", category="success")
    except ValidationError as e:
        buildings_logger.error(f"error raised when adding Unit : {str(e)}")
        flash(message="To Add a Unit please Fill in all Fields", category="danger")
    return redirect(url_for('buildings.get_building', building_id=building_id), code=302)


@buildings_route.get('/admin/building/<string:building_id>/unit/<string:unit_id>')
@login_required
async def get_unit(user: User, building_id: str, unit_id: str):
    """
        **get_unit**
            obtains rental unit
    :param user:
    :param building_id:
    :param unit_id:
    :return:
    """
    context = {}
    unit_data: Unit = await company_controller.get_unit(user=user, building_id=building_id, unit_id=unit_id)
    if unit_data and unit_data.tenant_id:
        tenant_data: Tenant = await tenant_controller.get_tenant_by_id(tenant_id=unit_data.tenant_id)
        context['tenant'] = tenant_data.dict()
        if tenant_data.company_id:
            company_data: Company = await company_controller.get_company_internal(company_id=tenant_data.company_id)
            if company_data:
                context['company'] = company_data.dict()
    else:
        tenants_list: list[Tenant] = await tenant_controller.get_un_booked_tenants()
        context['tenants'] = tenants_list

    billable_items_: list[BillableItem] = await company_controller.get_billable_items(building_id=building_id)
    billable_dicts: list[dict[str, str | int]] = [item.dict()
                                                  for item in billable_items_ if item] if billable_items else []

    charged_items_dicts = await build_charge_items(building_id, unit_id)

    if unit_data is None:
        flash(message="Could not find Unit with that ID", category="danger")
        redirect(url_for('buildings.get_building', building_id=building_id))

    context |= {
        'unit': unit_data,
        'billable_items': billable_dicts,
        'charged_items': charged_items_dicts,
    }

    return render_template('building/units/unit.html', **context)


async def build_charge_items(building_id, unit_id):
    charged_items = await company_controller.get_charged_items(building_id=building_id, unit_id=unit_id)

    charged_items_dicts = [item.dict() for item in charged_items if item] if charged_items else []
    response_data = []
    for item in charged_items_dicts:
        _data = item
        billable_item: BillableItem = await company_controller.get_item_by_number(item_number=item.get('item_number'))
        _data["item"] = billable_item.dict()
        response_data.append(_data)

    return response_data


@buildings_route.post('/admin/building/<string:building_id>/unit/<string:unit_id>')
@login_required
async def add_tenant_to_building_unit(user: User, building_id: str, unit_id: str):
    """
        add_tenant_to_building_unit
    :param user:
    :param building_id:
    :param unit_id:
    :return:
    """
    context = dict(user=user.dict())
    tenant_rental = Unit(**request.form)
    _updated_unit = await company_controller.update_unit(user_id=user.user_id, unit_data=tenant_rental)

    if _updated_unit:
        context |= dict(unit=_updated_unit.dict())

    tenant: Tenant = await tenant_controller.get_tenant_by_id(tenant_id=tenant_rental.tenant_id)
    tenant.is_renting = True
    tenant.lease_start_date = tenant_rental.lease_start_date
    tenant.lease_end_date = tenant_rental.lease_end_date
    updated_tenant = await tenant_controller.update_tenant(tenant=tenant)

    if updated_tenant:
        context |= dict(tenant=updated_tenant.dict())

    deposit_amount = await lease_agreement_controller.calculate_deposit_amount(
        rental_amount=tenant_rental.rental_amount)

    lease_dict: dict[str, str] = dict(property_id=tenant_rental.property_id,
                                      tenant_id=tenant_rental.tenant_id,
                                      unit_id=tenant_rental.unit_id,
                                      start_date=tenant_rental.lease_start_date,
                                      end_date=tenant_rental.lease_end_date,
                                      rent_amount=tenant_rental.rental_amount,
                                      deposit_amount=deposit_amount,

templates/building/add_building.html
{% extends "layouts/page.html" %}

{% block content %}
    <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="card">
                <div class="card-title">
                    <h2 class="card-title font-weight-bold">{{ company.company_name }}</h2>
                </div>
                <div class="card-footer">
                    <span class="text-info font-weight-bold">Use the form below to create a Property/Building for this Company</span>
                </div>

                <div class="card-body">
                <form action="{{ url_for('buildings.do_add_building', company_id=company.company_id) }}" method="post" enctype="application/x-www-form-urlencoded" class="container">
                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" id="name" name="name" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label for="description">Description:</label>
                        <textarea id="description" name="description" class="form-control" required></textarea>
                    </div>

                    <div class="form-group">
                        <label for="property_type">Property Type:</label>
                        <select id="property_type" name="property_type" class="form-control" required>
                            <option value="Residential">Residential</option>
                            <option value="Commercial">Commercial</option>
                            <option value="Industrial">Industrial</option>
                            <option value="Agricultural">Agricultural</option>
                            <option value="Mixed">Mixed</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="amenities">Amenities:</label>
                        <input type="text" id="amenities" name="amenities" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label for="landlord">Landlord:</label>
                        <input type="text" id="landlord" name="landlord" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label for="maintenance_contact">Maintenance Contact:</label>
                        <input type="text" id="maintenance_contact" name="maintenance_contact" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label for="lease_terms">Lease Terms:</label>
                        <textarea type="text" id="lease_terms" name="lease_terms" class="form-control" required> </textarea>
                    </div>

                    <div class="form-group">
                        <label for="built_year">Year Built:</label>
                        <input type="number" id="built_year" name="built_year" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label for="parking_spots">Parking Spots:</label>
                        <input type="number" id="parking_spots" name="parking_spots" class="form-control" required>
                    </div>
                    <button type="submit" value="Submit" class="btn btn-sm btn-primary"><i class="ti-save"> </i> Save</button>
                    <button type="reset" value="reset" class="btn btn-sm btn-danger"><i class="ti-close"> </i> Cancel</button>
                </form>
                </div>
            </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Property / Building</h3>
            </div>

            <div class="card-body">
                <h3 class="card-title"><i class="ti-info"></i> How to Add a Property</h3>
                <div class="card-content">
                    <p>
                        Follow the steps below to add a new property:
                    </p>
                    <ol class="list-group">
                        <li class="list-group-item"><span class="font-weight-bold">Fill in the necessary details in the form fields.</span></li>
                        <li  class="list-group-item"><span class="font-weight-bold">Click the "Update" button to save the changes.</span></li>
                        <li  class="list-group-item"><span class="font-weight-bold">If you want to cancel and discard the changes, click the "Cancel" button.</span></li>
                    </ol>
                </div>
                <hr />
                <div class="card-content">

                    <p class="font-weight-bold text-danger">
                        <i class="ti-wand"> </i>
                        Please ensure that all required fields are filled in correctly to successfully add the property.
                    </p>
                </div>
            </div>

            <div class="card-footer">
                <h3 class="card-title">NOTE</h3>
                <span class="card-content font-weight-bold font-italic">
                    <p>Buildings are used to organize the rental units.</p>
                    <p>Each building represents a physical structure or property that contains multiple units available for rent.</p>
                    <p>By grouping the units into buildings, it becomes easier to manage and categorize the properties within your rental management system.</p>
                    <p> You can assign specific details, such as the building name, address, property type, amenities, and more, to each building. </p>
                    <p> This helps in efficiently organizing and managing your rental properties.</p>
                </span>
            </div>

        </div>
    </div>
    </div>
{% endblock %}

templates/building/building.html
{% extends "layouts/page.html" %}
{% block custom_css %}
    <link href="{{ url_for('static', filename='css/property/unit.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#property-details"><strong>Property Details</strong></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#units-list"><strong>Units List</strong></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#billable"><strong>Billable Items</strong></a>
        </li>
    </ul>

    <div class="tab-content">
        <!-- Property Details -->
        <div id="property-details" class="tab-pane fade show active">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h3 class="card-title"><strong>{{ property.name }}</strong></h3>
                    <div>

                        <a href="{{ url_for('companies.get_company', company_id=property.company_id) }}" class="btn btn-sm btn-warning">
                            <i class="ti-desktop"> </i> Company
                        </a>
                        <button class="btn btn-sm btn-primary" data-toggle="modal" data-target="#addItemModal">
                            <i class="ti-money"> </i>
                            Billable Items
                        </button>
                        <a href="#" class="btn btn-sm btn-success" data-toggle="modal" data-target="#editPropertyDialog">
                            <i class="ti-desktop"> </i> Edit
                        </a>
                    </div>
                </div>

                {% include "building/tables/property_description.html" %}

                    <!-- include the building / Property Editor form here -->
                    {% if property_editor %}
                        {% include 'building/edit_building.html' %}
                    {% endif %}
            </div>
        </div>

        <!-- Units List -->
        <div id="units-list" class="tab-pane fade">
            <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h3 class="card-title"><span class="font-weight-bold">{{ property.name }}</span></h3>
                <div>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addPropertyUnitModal">
                        Add Property Unit
                    </button>
                </div>
            </div>
            </div>
            {% include "building/tables/unit_list.html" %}
        </div>

        <div id="billable" class="tab-pane fade">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h3 class="card-title"> Billable Items</h3>
                    <div>
                        <button class="btn btn-sm btn-primary"
                                data-toggle="modal"
                                data-target="#addItemModal">
                            <i class="ti-save"> </i>
                            Add
                        </button>
                    </div>

                </div>
                {% include "building/tables/billable_items.html" %}
            </div>
        </div>
    </div>

{# tab includes #}
{% include "building/modals/add_unit.html" %}
{% include "building/modals/edit_property.html" %}
{% include "building/modals/charged_items.html" %}

{% endblock %}

templates/building/buildings.html
{% extends "layouts/page.html" %}

{% block content %}
    <div class="card">
        <h4>List of Rental Properties</h4>
        <table class="table">
            <thead>
                <tr>
                    <th><i class="ti-home"></i>  Property Name</th>
                    <th><i class="ti-location-pin"></i> Location</th>
                    <th><i class="ti-layout-grid2"></i> Number of Units</th>
                    <th><i class="ti-money"></i> Rental Price</th>
                </tr>
            </thead>
            <tbody>
                {% for property in properties %}
                <tr>
                    <td><i class="ti-home"></i> <a href="#" class="alert-link"> {{ property.name }} </a></td>
                    <td><i class="ti-location-pin"></i> {{ property.location }}</td>
                    <td><i class="ti-layout-grid2"></i> {{ property.num_units }}</td>
                    <td><i class="ti-money"></i> {{ property.rental_price }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/building/edit_building.html
<form class="row m-b-2" action="{{ url_for('buildings.do_edit_building', building_id=property.property_id) }}" method="POST">
    <input type="hidden" name="property_id" value="{{ property.property_id }}" />
    <input type="hidden" name="company_id" value="{{ property.company_id }}" />
<div class="card-footer col-sm-12 col-lg-6 col-md-6">
    <div class="card-header">
        <h3 class="card-title">Property Editor...</h3>
    </div>
    <div class="card-body">

            <div class="form-group">
                <label class="label" for="name">Name</label>
                <input class="form-control" type="text" name="name" value="{{ property.name }}"/>
            </div>
            <div class="form-group">
                <label class="label" for="description">Description</label>
                <textarea class="form-control" name="description" >{{ property.description }}</textarea>
            </div>
            <div class="form-group">
                <label class="label" for="address">Address</label>
                <input class="form-control" type="text" name="address" value="{{ property.address }}"/>
            </div>
            <div class="form-group">
                <label class="label" for="property_type">Property Type</label>
                <input class="form-control" type="text" name="property_type" value="{{ property.property_type }}"/>
            </div>
            <div class="form-group">
                <label class="label" for="amenities">Amenities</label>
                <input class="form-control" type="text" name="amenities" value="{{ property.amenities }}"/>
            </div>
            <!-- Add more fields for other property details -->

    </div>
</div>

<div class="card-footer col-sm-12 col-lg-6 col-md-6">
    <div class="card-header">
        <h3 class="card-title">Editing ...</h3>
    </div>
    <div class="card-body">

            <div class="form-group">
                <label class="label" for="landlord">Name</label>
                <input class="form-control" type="text" name="landlord" value="{{ property.landlord }}"/>
            </div>
            <div class="form-group">
                <label class="label" for="maintenance_contact">Maintenance</label>
                <input class="form-control" type="text" name="maintenance_contact" value="{{ property.maintenance_contact }}"/>
            </div>
            <div class="form-group">
                <label class="label" for="lease_terms">Lease Terms</label>
                <textarea class="form-control" type="text" name="lease_terms">{{ property.lease_terms }} </textarea>
            </div>
            <div class="form-group">
                <label class="label" for="built_year">Built Year</label>
                <input class="form-control" type="number" name="built_year" value="{{ property.built_year }}"/>
            </div>
            <div class="form-group">
                <label class="label" for="parking_spots">Parking Spots</label>
                <input class="form-control" type="number" name="parking_spots" value="{{ property.parking_spots }}"/>
            </div>
            <!-- Add more fields for other property details -->

    </div>
</div>
    <div class="card-footer">
        <button class="btn btn-sm btn-primary"><i class="ti-save"> </i>  Update</button>
        <a href="{{ url_for('buildings.get_building', building_id=property.property_id) }}" class="btn btn-sm btn-danger">
        <i class="ti-close"></i> Cancel </a>
    </div>
</form>